#! /bin/sh

# sxhkd &

bspc monitor DVI-I-1-1 -d I II III IV V 
bspc monitor eDP1 -d VI VII VIII IX X

bspc config --monitor DVI-I-1-1 right_padding 0
bspc config --monitor DVI-I-1-1 bottom_padding 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config honor_size_hints     true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc rule -a qutebrowser desktop='^1' follow=on
bspc rule -a code-oss desktop='^5'
bspc rule -a Wfica desktop='^2' follow=on
bspc rule -a GLava state=floating layer=below sticky=true locked=true border=off
bspc rule -a Zathura state=tiled

#bspc rule -a Alacritty desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Start polybar
$HOME/.config/polybar/launch.sh

# Movement
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
